name: Build Buildkite-agent-metrics docker image
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - ".buildkite/**"
      - ".github/workflows/build-docker-img.yaml"
      - "backend/**"
      - "collector/**"
      - "token/**"
      - "version/**"
      - "lambda/**"
      - "Dockerfile"
      - "main.go"
env:
  BUILD_ENV: production
  CLOUDFLARE_ACCOUNT_ID: 4402523d2537f701a064d23781760a0e
jobs:
  build_docker_image:
    name: Build buildkite-agent-metrics docker image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4 
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets..DOCKERHUB_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/buildkite-agent-metrics:latest
